# Templates for linux, macOS, and Windows
# Based on approach from conda-forge

stages:
- stage: Preparation
  displayName: Download
  jobs:
    - template: ./download-source.yml
    - template: ./download-conda.yml

- stage: Build
  displayName: Build and test
  dependsOn: Preparation
  jobs:
    - template: ./conda-linux.yml
      parameters:
        distribution: centos
        version: [6, 10]
    - template: ./conda-osx.yml
      parameters:
        vmImage: [10, 14]
        xcode_version: [10, 3]
